name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-linux-amd64:
    name: Build Linux (Intel/AMD)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Install C Compiler for SQLite
      run: sudo apt-get update && sudo apt-get install -y gcc libc6-dev
    - name: Build
      env:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: amd64
      run: go build -ldflags="-s -w" -o quicknote-linux-amd64 .
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} quicknote-linux-amd64

  build-mac-intel:
    name: Build Mac (Intel)
    runs-on: macos-13 # Explicitly requests an Intel Mac server
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: amd64
      run: go build -ldflags="-s -w" -o quicknote-darwin-amd64 .
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} quicknote-darwin-amd64

  build-mac-arm:
    name: Build Mac (Apple Silicon)
    runs-on: macos-14 # Explicitly requests an M-Series Mac server
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: arm64
      run: go build -ldflags="-s -w" -o quicknote-darwin-arm64 .
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} quicknote-darwin-arm64